version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scholar-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8989
      - NEXT_PUBLIC_DOCKER_BACKEND_URL=http://localhost:8989
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=923685198285-bcuenjqssub489v92n9m3fgmeo1qv19f.apps.googleusercontent.com
      - NEXT_PUBLIC_GITHUB_CLIENT_ID=Ov23lib9rnCavmUN37Qf
      - NEXT_PUBLIC_ENV=docker
    networks:
      - scholarai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  scholarai-network:
    external: true
    name: docker_scholarai-network
