services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scholar-frontend

    # 🏷️ Add metadata labels for cleanup & observability
    labels:
      service: "frontend"
      maintainer: "ScholarAI <dev@scholarai.local>"
      version: "0.0.1-SNAPSHOT"
      description: "Next.js Frontend for ScholarAI"
    env_file:
      - /opt/scholarai/envs/frontend.env
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_ENV=prod
    networks:
      - scholarai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  scholarai-network:
    external: true
    name: docker_scholarai-network
