services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scholar-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DEV_API_URL=${NEXT_PUBLIC_DEV_API_URL}
      - NEXT_PUBLIC_DOCKER_BACKEND_URL=${NEXT_PUBLIC_DOCKER_BACKEND_URL}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - NEXT_PUBLIC_GITHUB_CLIENT_ID=${NEXT_PUBLIC_GITHUB_CLIENT_ID}
      - NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV}
      - B2_KEY_ID=${B2_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME}
      - B2_BUCKET_ID=${B2_BUCKET_ID}
    networks:
      - scholarai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  scholarai-network:
    external: true
    name: docker_scholarai-network
